[package]
name = "overtone-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[lints]
workspace = true

[[bin]]
name = "overtone-cli"
path = "src/main.rs"

[dependencies]
overtone-audio = { version = "0.2.0-alpha", path = "../overtone-audio" }
overtone-core = { version = "0.2.0-alpha", path = "../overtone-core" }
overtone-dsp = { version = "0.2.0-alpha", path = "../overtone-dsp" }
overtone-hitsound = { version = "0.2.0-alpha", path = "../overtone-hitsound" }
overtone-tempo = { version = "0.2.0-alpha", path = "../overtone-tempo" }
serde_json = "1.0.151"
