//! The binary end to end: exit codes, stdout carrying only the result, and
//! the report's shape. Audio is synthesised into a scratch directory.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn scratch(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("overtone-cli-{tag}-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// 16-bit mono PCM WAV at 44.1 kHz.
fn write_wav(path: &Path, samples: &[f32]) {
    let data = (samples.len() * 2) as u32;
    let mut b = Vec::new();
    b.extend_from_slice(b"RIFF");
    b.extend_from_slice(&(36 + data).to_le_bytes());
    b.extend_from_slice(b"WAVEfmt ");
    b.extend_from_slice(&16u32.to_le_bytes());
    b.extend_from_slice(&1u16.to_le_bytes());
    b.extend_from_slice(&1u16.to_le_bytes());
    b.extend_from_slice(&44_100u32.to_le_bytes());
    b.extend_from_slice(&(44_100u32 * 2).to_le_bytes());
    b.extend_from_slice(&2u16.to_le_bytes());
    b.extend_from_slice(&16u16.to_le_bytes());
    b.extend_from_slice(b"data");
    b.extend_from_slice(&data.to_le_bytes());
    for &s in samples {
        b.extend_from_slice(&((s.clamp(-1.0, 1.0) * 32767.0) as i16).to_le_bytes());
    }
    std::fs::write(path, b).unwrap();
}

/// Deterministic noise in [-0.5, 0.5).
fn noise(seed: &mut u64) -> f32 {
    *seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1);
    ((*seed >> 33) as f64 / (1u64 << 31) as f64 - 0.5) as f32
}

/// Clicks at `bpm` from 0.5 s for `seconds`, every fourth one louder.
fn clicks(bpm: f64, seconds: f64) -> Vec<f32> {
    let sr = 44_100.0;
    let mut y = vec![0.0f32; (seconds * sr) as usize];
    let mut seed = 7u64;
    let mut k = 0usize;
    loop {
        let t = 0.5 + k as f64 * 60.0 / bpm;
        if t > seconds - 0.2 {
            break;
        }
        let gain = if k % 4 == 0 { 0.9 } else { 0.5 };
        let start = (t * sr) as usize;
        for i in 0..(0.03 * sr) as usize {
            let decay = (-(i as f64) / (0.004 * sr)).exp() as f32;
            y[start + i] += gain * decay * noise(&mut seed);
        }
        k += 1;
    }
    y
}

/// 16-bit mono PCM WAV at any rate.
fn write_wav_at(path: &Path, samples: &[f32], rate: u32) {
    write_wav(path, samples);
    let mut bytes = std::fs::read(path).unwrap();
    bytes[24..28].copy_from_slice(&rate.to_le_bytes());
    bytes[28..32].copy_from_slice(&(rate * 2).to_le_bytes());
    std::fs::write(path, bytes).unwrap();
}

/// Clicks at `bpm` rendered at `rate`, as [`clicks`] does at 44.1 kHz.
fn clicks_at(bpm: f64, seconds: f64, rate: u32) -> Vec<f32> {
    let sr = rate as f64;
    let mut y = vec![0.0f32; (seconds * sr) as usize];
    let mut seed = 7u64;
    let mut k = 0usize;
    loop {
        let t = 0.5 + k as f64 * 60.0 / bpm;
        if t > seconds - 0.2 {
            break;
        }
        let gain = if k % 4 == 0 { 0.9 } else { 0.5 };
        let start = (t * sr) as usize;
        for i in 0..(0.03 * sr) as usize {
            let decay = (-(i as f64) / (0.004 * sr)).exp() as f32;
            y[start + i] += gain * decay * noise(&mut seed);
        }
        k += 1;
    }
    y
}

fn run(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_overtone-cli"))
        .args(args)
        .output()
        .expect("the binary runs")
}

#[test]
fn a_click_track_reads_its_tempo() {
    let dir = scratch("clicks");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 30.0));
    let json_run = run(&["analyze", path.to_str().unwrap(), "--json"]);
    let text_run = run(&["analyze", path.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        json_run.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&json_run.stderr)
    );
    let report: serde_json::Value =
        serde_json::from_slice(&json_run.stdout).expect("stdout is one JSON document");
    let bpm = report["global_bpm"].as_f64().unwrap();
    assert!((bpm - 150.0).abs() < 0.05, "global bpm {bpm}");
    assert_eq!(report["engine"], "precision");
    let points = report["points"].as_array().unwrap();
    assert!(!points.is_empty());
    let first = points[0]["offset_ms"].as_f64().unwrap();
    assert!((first - 500.0).abs() < 5.0, "first red line at {first} ms");
    assert!(report["diagnostics"].as_array().unwrap().is_empty());
    // v3's findings are not ported: absent, not an empty "nothing found".
    assert!(report.get("findings").is_none());

    assert_eq!(text_run.status.code(), Some(0));
    let text = String::from_utf8(text_run.stdout).unwrap();
    let mut lines = text.lines();
    assert!(lines
        .next()
        .unwrap()
        .starts_with("// Generated by Overtone v"));
    let row = lines.next().expect("one red line at least");
    assert_eq!(row.split(',').count(), 8, "{row}");
    // Progress went to stderr, not into the red lines.
    assert!(!text.contains("decoded"));
    assert!(String::from_utf8_lossy(&text_run.stderr).contains("decoded"));
}

#[test]
fn white_noise_is_refused_with_its_reason() {
    let dir = scratch("noise");
    let path = dir.join("noise.wav");
    let mut seed = 99u64;
    let y: Vec<f32> = (0..44_100 * 10).map(|_| 0.8 * noise(&mut seed)).collect();
    write_wav(&path, &y);
    let json_run = run(&["analyze", path.to_str().unwrap(), "--json"]);
    let text_run = run(&["analyze", path.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(json_run.status.code(), Some(3));
    let report: serde_json::Value = serde_json::from_slice(&json_run.stdout).unwrap();
    assert!(report["global_bpm"].is_null(), "no BPM for noise: {report}");
    assert_eq!(report["engine"], "refused");
    assert!(report["points"].as_array().unwrap().is_empty());
    assert!(!report["diagnostics"].as_array().unwrap().is_empty());

    assert_eq!(text_run.status.code(), Some(3));
    assert!(text_run.stdout.is_empty(), "no red lines on stdout");
}

#[test]
fn a_missing_file_and_a_bad_command_line_say_so() {
    let missing = run(&["analyze", "no-such-file.wav", "--json"]);
    assert_eq!(missing.status.code(), Some(1));
    let report: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert!(report["error"].is_string());

    for args in [
        &[][..],
        &["analyse", "x.wav"][..],
        &["analyze"][..],
        &["analyze", "a.wav", "b.wav"][..],
        &["analyze", "a.wav", "--decimals"][..],
        &["analyze", "a.wav", "--persistence", "many"][..],
        &["analyze", "a.wav", "--frobnicate"][..],
    ] {
        let out = run(args);
        assert_eq!(out.status.code(), Some(2), "{args:?}");
        assert!(out.stdout.is_empty(), "{args:?}");
        assert!(String::from_utf8_lossy(&out.stderr).contains("usage:"));
    }
}

#[test]
fn odd_rates_short_audio_and_junk_end_cleanly() {
    // The gates.py robustness probes, through the v4 engine.
    let dir = scratch("robust");
    let mut reports = Vec::new();
    for rate in [8_000u32, 96_000] {
        let path = dir.join(format!("clicks-{rate}.wav"));
        write_wav_at(&path, &clicks_at(150.0, 20.0, rate), rate);
        reports.push((rate, run(&["analyze", path.to_str().unwrap(), "--json"])));
    }
    let short = dir.join("short.wav");
    write_wav(&short, &clicks(150.0, 1.0));
    let short_run = run(&["analyze", short.to_str().unwrap()]);
    let junk = dir.join("notes.wav");
    std::fs::write(&junk, "not audio at all").unwrap();
    let junk_run = run(&["analyze", junk.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    for (rate, out) in reports {
        assert_eq!(out.status.code(), Some(0), "{rate} Hz");
        let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
        let bpm = report["global_bpm"].as_f64().unwrap();
        assert!((bpm - 150.0).abs() < 0.05, "{rate} Hz read {bpm}");
    }
    // Exit 1 (could not load), with a message: not a panic (exit 101).
    for out in [short_run, junk_run] {
        assert_eq!(out.status.code(), Some(1));
        assert!(out.stdout.is_empty());
        assert!(String::from_utf8_lossy(&out.stderr).contains("cannot load"));
    }
}

#[test]
fn full_carries_the_evidence_an_analysis_object_needs() {
    let dir = scratch("full");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 30.0));
    let out = run(&["analyze", path.to_str().unwrap(), "--full"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(out.status.code(), Some(0));
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let evidence = &report["evidence"];
    assert_eq!(evidence["hop"], 128);
    assert_eq!(evidence["sample_rate"], 44_100);
    let len = |key: &str| evidence[key].as_array().unwrap().len();
    // The fitting envelope has librosa's centred frame count: 1 + n / hop.
    assert_eq!(len("onset"), 1 + 30 * 44_100 / 128);
    assert_eq!(len("attack_times"), len("attack_weights"));
    assert!(len("attack_times") >= 70, "{} attacks", len("attack_times"));
    assert!(len("beats") >= 70);
    assert_eq!(len("local_bpms"), len("beats"));
    assert!(len("points") >= 1);
    // Sections now say where their grid is, not only its tempo.
    let section = &report["sections"][0];
    let period = section["period_s"].as_f64().unwrap();
    assert!((60.0 / period - 150.0).abs() < 0.05, "period {period}");
    assert!(section["phase_s"].is_number());
}

/// A sustained triad, `seconds` long, at `amp`.
fn triad(root: f64, amp: f64, seconds: f64) -> Vec<f32> {
    let sr = 44_100.0;
    (0..(seconds * sr) as usize)
        .map(|i| {
            let t = i as f64 / sr;
            let tau = 2.0 * std::f64::consts::PI * t;
            (amp * ((tau * root).sin()
                + 0.6 * (tau * root * 1.2599).sin()
                + 0.6 * (tau * root * 1.4983).sin())) as f32
        })
        .collect()
}

/// A part of a song: one triad per half second, root and quality drawn
/// from `seed`, so a part played again is the same part.
fn part(seed: u64, seconds: f64, amp: f64) -> Vec<f32> {
    let mut state = seed.wrapping_mul(0x9e37_79b9_7f4a_7c15) | 1;
    let mut out = Vec::new();
    for _ in 0..(seconds * 2.0).round() as usize {
        state ^= state << 13;
        state ^= state >> 7;
        state ^= state << 17;
        let root = 110.0 * 2f64.powf((state % 24) as f64 / 12.0);
        out.extend(triad(root, amp, 0.5));
    }
    out
}

#[test]
fn structure_reads_phrases_and_says_why_each_label() {
    // An intro, then A B C A C B: 12 s parts of changing chords, each back
    // once at its own distance and each louder than the last. The edges
    // are where the song starts or stops repeating: 8/20/32/44/56/68.
    let dir = scratch("structure");
    let path = dir.join("iabcacb.wav");
    let (a, b, c) = (part(1, 12.0, 0.05), part(2, 12.0, 0.1), part(3, 12.0, 0.2));
    write_wav(
        &path,
        &[part(9, 8.0, 0.05), a.clone(), b.clone(), c.clone(), a, c, b].concat(),
    );
    let out = run(&["structure", path.to_str().unwrap()]);
    let missing = run(&["structure", "no-such-file.wav"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let bounds: Vec<f64> = report["boundaries"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    assert_eq!(bounds.len(), 6, "{bounds:?}");
    for (found, truth) in bounds.iter().zip([8.0, 20.0, 32.0, 44.0, 56.0, 68.0]) {
        assert!((found - truth).abs() <= 1.5, "{bounds:?}");
    }
    let sections = report["sections"].as_array().unwrap();
    let kinds: Vec<&str> = sections
        .iter()
        .map(|s| s["kind"].as_str().unwrap())
        .collect();
    let groups: Vec<u64> = sections
        .iter()
        .map(|s| s["group"].as_u64().unwrap())
        .collect();
    let repeats: Vec<u64> = sections
        .iter()
        .map(|s| s["repeats"].as_u64().unwrap())
        .collect();
    // C, twice and loudest, is the chorus; the intro, A and B share one
    // family.
    assert_eq!(kinds, ["verse", "verse", "verse", "chorus", "verse", "chorus", "verse"]);
    assert_eq!(groups, [0, 0, 0, 1, 0, 1, 0]);
    assert_eq!(repeats, [5, 5, 5, 2, 5, 2, 5]);
    assert!(sections[3]["level_db"].as_f64().unwrap() > sections[2]["level_db"].as_f64().unwrap());
    let energy = report["energy"].as_array().unwrap().len();
    assert_eq!(energy, 160, "one value per 0.5 s window");
    assert_eq!(report["rules"]["edge_blind_s"], 4.0);
    assert!(report["rules"]["edge_over_median"].is_number());

    assert_eq!(missing.status.code(), Some(1));
    let failed: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert!(failed["error"].is_string());
    for args in [
        &["structure"][..],
        &["structure", "a.wav", "b.wav"][..],
        &["structure", "--full"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
        assert!(bad.stdout.is_empty());
    }
}

#[test]
fn hitsound_proposes_every_object_with_alternatives_and_terms() {
    // Twelve bare circles on 150 BPM clicks: the prior keeps them bare,
    // and each proposal carries its alternatives, its terms and what was
    // heard under it. A thirteenth circle between two clicks hears nothing.
    let dir = scratch("hitsound");
    let audio = dir.join("clicks-150.wav");
    write_wav(&audio, &clicks(150.0, 6.0));
    let mut map = String::from("osu file format v14\r\n[TimingPoints]\r\n500,400,4,2,1,70,1,0\r\n[HitObjects]\r\n");
    for k in 0..12 {
        map.push_str(&format!("256,192,{},1,0,0:0:0:0:\r\n", 500 + k * 400));
    }
    map.push_str("256,192,5100,1,0,0:0:0:0:\r\n");
    let map_path = dir.join("clicks.osu");
    std::fs::write(&map_path, map).unwrap();
    let out = run(&["hitsound", audio.to_str().unwrap(), map_path.to_str().unwrap()]);
    let missing_map = run(&["hitsound", audio.to_str().unwrap(), "no-such.osu"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(report["templates"], "baked");
    assert_eq!(report["profile"], "balanced");
    let units = report["units"].as_array().unwrap();
    assert_eq!(units.len(), 13);
    for unit in &units[..12] {
        // Heard: the click under it, its likeliest instruments best first.
        let heard = &unit["heard"];
        let at = heard["time_ms"].as_f64().unwrap();
        assert!((at - unit["time_ms"].as_f64().unwrap()).abs() <= 50.0, "{heard}");
        let classes = heard["classes"].as_array().unwrap();
        assert!((1..=3).contains(&classes.len()));
        let p: Vec<f64> = classes.iter().map(|c| c["probability"].as_f64().unwrap()).collect();
        assert!(p.windows(2).all(|w| w[0] >= w[1]) && p.iter().all(|x| (0.0..=1.0).contains(x)));
        assert!(classes.iter().all(|c| c["class"].is_string()));
        assert!(heard["metrical_weight"].is_number() || heard["metrical_weight"].is_null());
    }
    assert!(units[12]["heard"].is_null(), "{}", units[12]["heard"]);
    for unit in units {
        let proposal = &unit["proposal"];
        assert!(proposal["bank"].is_string());
        assert!(proposal["additions"].is_array());
        let probability = proposal["probability"].as_f64().unwrap();
        assert!((0.0..=1.0).contains(&probability), "{proposal}");
        // Alternatives with marginals, terms that replay the choice.
        let alternatives = unit["alternatives"].as_array().unwrap();
        assert!(!alternatives.is_empty());
        assert!(alternatives.iter().all(|a| (0.0..=1.0).contains(&a["probability"].as_f64().unwrap())));
        let terms = unit["terms"].as_array().unwrap();
        assert_eq!(terms.len(), 4);
        assert!(unit["transition_in"].is_number() || unit["transition_in"].is_null());
        assert_eq!(unit["tail"], false);
    }
    // Bare circles with a prior stay bare: the first proposal is normal.
    assert_eq!(units[0]["proposal"]["additions"].as_array().unwrap().len(), 0);
    assert!(report["timings_s"]["decide"].is_number());

    assert_eq!(missing_map.status.code(), Some(1));
    for args in [
        &["hitsound"][..],
        &["hitsound", "a.wav", "b.osu", "--profile"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
    }
    // No map is the audio-only proposal now, not a usage error: a missing
    // audio file fails the load instead.
    for args in [
        &["hitsound", "a.wav"][..],
        &["hitsound", "a.wav", "--profile", "p.json"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(1), "{args:?}");
    }
}

#[test]
fn hitsound_without_a_map_proposes_on_the_songs_own_attacks() {
    // H7: strong attacks on the detected grid become the object set — no
    // object numbers, no combos, no prior — marked audio-only. Silence has
    // nothing strong, so it proposes nothing and still exits 0.
    let dir = scratch("hitsound-audio-only");
    let audio = dir.join("clicks-150.wav");
    write_wav(&audio, &clicks(150.0, 6.0));
    let silence = dir.join("silence.wav");
    write_wav(&silence, &vec![0.0f32; 44_100 * 3]);
    let out = run(&["hitsound", audio.to_str().unwrap()]);
    let quiet = run(&["hitsound", silence.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(report["mode"], "audio-only");
    assert_eq!(report["templates"], "baked");
    assert_eq!(report["profile"], "balanced");
    let units = report["units"].as_array().unwrap();
    assert!(!units.is_empty());
    for unit in units {
        assert!(unit["object"].is_null());
        assert_eq!(unit["part"], "attack");
        assert!(unit["edge"].is_null());
        assert_eq!(unit["tail"], false);
        assert!(unit["follows"].is_null());
        // Heard is its own attack: the click under it, within the P-5 window.
        let heard = &unit["heard"];
        let at = heard["time_ms"].as_f64().unwrap();
        assert!((at - unit["time_ms"].as_f64().unwrap()).abs() <= 50.0, "{heard}");
        let proposal = &unit["proposal"];
        assert!(proposal["bank"].is_string());
        assert!(proposal["additions"].is_array());
        assert!((0.0..=1.0).contains(&proposal["probability"].as_f64().unwrap()));
        assert!(!unit["alternatives"].as_array().unwrap().is_empty());
        assert_eq!(unit["terms"].as_array().unwrap().len(), 4);
    }
    // Times run with the clicks: the first strong attack sits on the grid.
    let first = units[0]["time_ms"].as_f64().unwrap();
    assert!((first - 500.0).abs() < 100.0, "{first}");

    assert_eq!(
        quiet.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&quiet.stderr)
    );
    let empty: serde_json::Value = serde_json::from_slice(&quiet.stdout).unwrap();
    assert_eq!(empty["mode"], "audio-only");
    assert!(empty["units"].as_array().unwrap().is_empty());
}

/// A map of circles on the 150 BPM clicks, every one playing `bits`.
fn circles(times_ms: &[u32], bits: u8) -> String {
    let mut map = String::from("osu file format v14\r\n[TimingPoints]\r\n500,400,4,2,1,70,1,0\r\n[HitObjects]\r\n");
    for t in times_ms {
        map.push_str(&format!("256,192,{t},1,{bits},0:0:0:0:\r\n"));
    }
    map
}

fn sorted_keys(value: &serde_json::Value) -> Vec<String> {
    let mut keys: Vec<String> = value.as_object().unwrap().keys().cloned().collect();
    keys.sort();
    keys
}

#[test]
fn hitsound_decides_several_maps_on_one_analysis() {
    // Two difficulties of one song and a third that is not there: the song
    // is analysed once, each map gets exactly the proposals its own run
    // gives, and the missing one is that map's error alone.
    let dir = scratch("hitsound-maps");
    let audio = dir.join("clicks-150.wav");
    write_wav(&audio, &clicks(150.0, 6.0));
    let (easy, hard, gone) = (dir.join("easy.osu"), dir.join("hard.osu"), dir.join("insane.osu"));
    std::fs::write(&easy, circles(&[500, 1300, 2100, 2900, 3700], 0)).unwrap();
    std::fs::write(&hard, circles(&(0..12).map(|k| 500 + k * 400).collect::<Vec<_>>(), 2)).unwrap();
    let (a, e, h, g) = (
        audio.to_str().unwrap(),
        easy.to_str().unwrap(),
        hard.to_str().unwrap(),
        gone.to_str().unwrap(),
    );
    let alone = [run(&["hitsound", a, e]), run(&["hitsound", a, h])];
    let batched = run(&["hitsound", a, e, g, h]);
    let no_audio = run(&["hitsound", "no-such.wav", e, h]);
    std::fs::remove_dir_all(&dir).ok();

    // One map keeps the one-map report, key for key.
    let reports: Vec<serde_json::Value> = alone
        .iter()
        .map(|out| {
            assert_eq!(out.status.code(), Some(0), "{}", String::from_utf8_lossy(&out.stderr));
            serde_json::from_slice(&out.stdout).unwrap()
        })
        .collect();
    assert_eq!(
        sorted_keys(&reports[0]),
        ["duration", "map", "profile", "source", "templates", "timings_s", "units", "version"]
    );
    assert_eq!(
        sorted_keys(&reports[0]["timings_s"]),
        ["attacks", "decide", "decode", "evidence", "structure", "tempo"]
    );
    assert_ne!(reports[0]["units"], reports[1]["units"]);

    // Several: the song once, then its maps in the order given; the one
    // that cannot be read makes the exit 1 and fails no other.
    assert_eq!(batched.status.code(), Some(1), "{}", String::from_utf8_lossy(&batched.stderr));
    let report: serde_json::Value = serde_json::from_slice(&batched.stdout).unwrap();
    assert_eq!(
        sorted_keys(&report),
        ["duration", "maps", "profile", "source", "templates", "timings_s", "version"]
    );
    assert_eq!(
        sorted_keys(&report["timings_s"]),
        ["attacks", "decode", "evidence", "structure", "tempo"]
    );
    assert_eq!((&report["duration"], &report["profile"]), (&reports[0]["duration"], &reports[0]["profile"]));
    let maps = report["maps"].as_array().unwrap();
    let paths: Vec<&str> = maps.iter().map(|m| m["map"].as_str().unwrap()).collect();
    assert_eq!(paths, [e, g, h]);
    assert_eq!(maps[0]["units"], reports[0]["units"]);
    assert_eq!(maps[2]["units"], reports[1]["units"]);
    assert!(maps[0]["timings_s"]["decide"].is_number());
    assert!(maps[1]["error"].as_str().unwrap().starts_with("cannot read"), "{}", maps[1]);
    assert_eq!(sorted_keys(&maps[1]), ["error", "map"]);

    // An audio that cannot be read fails every map at once, and says which.
    assert_eq!(no_audio.status.code(), Some(1));
    let failed: serde_json::Value = serde_json::from_slice(&no_audio.stdout).unwrap();
    assert!(failed["error"].as_str().unwrap().starts_with("cannot load"), "{failed}");
    assert_eq!(failed["maps"], serde_json::json!([e, h]));
}

#[test]
fn ramps_turns_a_click_track_into_one_line_and_refuses_bad_input() {
    let dir = scratch("ramps");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 30.0));
    let out = run(&["ramps", path.to_str().unwrap()]);
    let capped = run(&["ramps", path.to_str().unwrap(), "--max-lines", "1"]);
    let missing = run(&["ramps", "no-such-file.wav"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let lines = report["lines"].as_array().unwrap();
    assert_eq!(lines.len(), 1, "{lines:?}");
    let bpm = lines[0]["bpm"].as_f64().unwrap();
    assert!((bpm - 150.0).abs() < 0.5, "one line at {bpm}");
    assert!(lines[0]["max_drift_ms"].as_f64().unwrap() <= 5.0);
    let tradeoff = report["tradeoff"].as_array().unwrap();
    assert_eq!(tradeoff.len(), 5);
    assert!(tradeoff.iter().all(|row| row["lines"].as_u64().unwrap() == 1));
    assert_eq!(report["recommend_ramps"], false);
    assert_eq!(report["elastic"]["degree"].as_u64().unwrap(), 1);

    assert_eq!(capped.status.code(), Some(0));
    let capped_report: serde_json::Value = serde_json::from_slice(&capped.stdout).unwrap();
    assert_eq!(capped_report["drift_ms"].as_f64().unwrap(), 1.0);

    assert_eq!(missing.status.code(), Some(1));
    for args in [
        &["ramps"][..],
        &["ramps", "a.wav", "b.wav"][..],
        &["ramps", "a.wav", "--drift", "0"][..],
        &["ramps", "a.wav", "--max-lines", "0"][..],
        &["ramps", "a.wav", "--bogus"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
    }
}

#[test]
fn hitsound_evidence_scores_every_attack_and_names_its_role() {
    let dir = scratch("evidence");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 12.0));
    let out = run(&["hitsound-evidence", path.to_str().unwrap()]);
    let missing = run(&["hitsound-evidence", "no-such-file.wav"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(report["templates"], "baked");
    let attacks = report["attacks"].as_array().unwrap();
    assert!(!attacks.is_empty());
    for attack in attacks {
        let classes = attack["classes"].as_array().unwrap();
        // All 13 classes, probabilities that sum to one.
        assert_eq!(classes.len(), 13, "{attack}");
        let total: f64 = classes
            .iter()
            .map(|c| c["probability"].as_f64().unwrap())
            .sum();
        assert!((total - 1.0).abs() < 1e-9, "{total}");
        // Each term's contribution replays its class's score.
        for class in classes {
            let terms = class["terms"].as_array().unwrap();
            assert!(!terms.is_empty());
            assert!(terms.iter().all(|t| t["feature"].is_string()
                && t["value"].is_number()
                && t["response"]["kind"].is_string()
                && t["contribution"].is_number()));
        }
        // The click grid proves bars, so the role sits on it.
        assert!(attack["role"]["division"].is_number());
        assert!(attack["role"]["metrical_weight"].is_number());
    }
    assert!(!report["sections"].as_array().unwrap().is_empty());

    assert_eq!(missing.status.code(), Some(1));
    for args in [
        &["hitsound-evidence"][..],
        &["hitsound-evidence", "a.wav", "b.wav"][..],
        &["hitsound-evidence", "--full"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
    }
}

#[test]
fn hitsound_classify_names_isolated_samples_best_first() {
    use overtone_hitsound::corpus::{self, HitClass};
    let dir = scratch("classify");
    let kick = corpus::render(44_100, 2.0, 10.0, &[HitClass::Kick], 5);
    assert_eq!(kick.hits.len(), 1);
    let kick_path = dir.join("kick.wav");
    write_wav(&kick_path, &kick.samples);
    let silence_path = dir.join("silence.wav");
    write_wav(&silence_path, &vec![0.0f32; 44_100]);
    let out = run(&[
        "hitsound-classify",
        kick_path.to_str().unwrap(),
        silence_path.to_str().unwrap(),
    ]);
    let again = run(&[
        "hitsound-classify",
        kick_path.to_str().unwrap(),
        silence_path.to_str().unwrap(),
    ]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    // Deterministic: the same files read the same twice.
    assert_eq!(out.stdout, again.stdout);
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(report["templates"], "baked");
    let files = report["files"].as_array().unwrap();
    assert_eq!(files.len(), 2);
    for file in files {
        let classes = file["classes"].as_array().unwrap();
        // All 13 classes, best first, probabilities that sum to one, and
        // the top row repeating the winner.
        assert_eq!(classes.len(), 13, "{file}");
        let total: f64 = classes
            .iter()
            .map(|c| c["probability"].as_f64().unwrap())
            .sum();
        assert!((total - 1.0).abs() < 1e-9, "{total}");
        let mut probs: Vec<f64> = classes
            .iter()
            .map(|c| c["probability"].as_f64().unwrap())
            .collect();
        let mut sorted = probs.clone();
        sorted.sort_by(|a, b| b.total_cmp(a));
        assert_eq!(probs, sorted, "{file}");
        assert_eq!(file["top"], classes[0]["class"]);
        assert_eq!(
            file["probability"],
            classes[0]["probability"],
            "{file}"
        );
    }
    // The rendered kick starts at 0.5 s with a real onset, so the detector
    // — not the energy fallback — names its time.
    assert!(
        (files[0]["attack_s"].as_f64().unwrap() - 0.5).abs() < 0.05,
        "{}",
        files[0]
    );
    // Silence has no attack to find and nothing to be: null time, Other.
    assert!(files[1]["attack_s"].is_null());
    assert_eq!(files[1]["top"], "other");
    assert_eq!(files[1]["probability"], 1.0);
}

#[test]
fn hitsound_classify_reads_short_files_and_reports_the_unreadable() {
    // A hitsound is shorter than a song by design: half a second of tone
    // classifies instead of refusing at the two-second floor.
    let dir = scratch("classify-short");
    let short = dir.join("blip.wav");
    let tone: Vec<f32> = (0..22_050)
        .map(|i| {
            (0.5 * (std::f64::consts::TAU * 440.0 * i as f64 / 44_100.0).sin()) as f32
        })
        .collect();
    write_wav(&short, &tone);
    let out = run(&[
        "hitsound-classify",
        short.to_str().unwrap(),
        "no-such-file.wav",
    ]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(out.status.code(), Some(1));
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let files = report["files"].as_array().unwrap();
    assert_eq!(files.len(), 2);
    assert!(files[0]["top"].is_string());
    assert!(files[1]["error"].is_string());
    for args in [&["hitsound-classify"][..], &["hitsound-classify", "--json"][..]] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
    }
}
