//! The binary end to end: exit codes, stdout carrying only the result, and
//! the report's shape. Audio is synthesised into a scratch directory.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn scratch(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("overtone-cli-{tag}-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// 16-bit mono PCM WAV at 44.1 kHz.
fn write_wav(path: &Path, samples: &[f32]) {
    let data = (samples.len() * 2) as u32;
    let mut b = Vec::new();
    b.extend_from_slice(b"RIFF");
    b.extend_from_slice(&(36 + data).to_le_bytes());
    b.extend_from_slice(b"WAVEfmt ");
    b.extend_from_slice(&16u32.to_le_bytes());
    b.extend_from_slice(&1u16.to_le_bytes());
    b.extend_from_slice(&1u16.to_le_bytes());
    b.extend_from_slice(&44_100u32.to_le_bytes());
    b.extend_from_slice(&(44_100u32 * 2).to_le_bytes());
    b.extend_from_slice(&2u16.to_le_bytes());
    b.extend_from_slice(&16u16.to_le_bytes());
    b.extend_from_slice(b"data");
    b.extend_from_slice(&data.to_le_bytes());
    for &s in samples {
        b.extend_from_slice(&((s.clamp(-1.0, 1.0) * 32767.0) as i16).to_le_bytes());
    }
    std::fs::write(path, b).unwrap();
}

/// Deterministic noise in [-0.5, 0.5).
fn noise(seed: &mut u64) -> f32 {
    *seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1);
    ((*seed >> 33) as f64 / (1u64 << 31) as f64 - 0.5) as f32
}

/// Clicks at `bpm` from 0.5 s for `seconds`, every fourth one louder.
fn clicks(bpm: f64, seconds: f64) -> Vec<f32> {
    let sr = 44_100.0;
    let mut y = vec![0.0f32; (seconds * sr) as usize];
    let mut seed = 7u64;
    let mut k = 0usize;
    loop {
        let t = 0.5 + k as f64 * 60.0 / bpm;
        if t > seconds - 0.2 {
            break;
        }
        let gain = if k % 4 == 0 { 0.9 } else { 0.5 };
        let start = (t * sr) as usize;
        for i in 0..(0.03 * sr) as usize {
            let decay = (-(i as f64) / (0.004 * sr)).exp() as f32;
            y[start + i] += gain * decay * noise(&mut seed);
        }
        k += 1;
    }
    y
}

fn run(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_overtone-cli"))
        .args(args)
        .output()
        .expect("the binary runs")
}

#[test]
fn a_click_track_reads_its_tempo() {
    let dir = scratch("clicks");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 30.0));
    let json_run = run(&["analyze", path.to_str().unwrap(), "--json"]);
    let text_run = run(&["analyze", path.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        json_run.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&json_run.stderr)
    );
    let report: serde_json::Value =
        serde_json::from_slice(&json_run.stdout).expect("stdout is one JSON document");
    let bpm = report["global_bpm"].as_f64().unwrap();
    assert!((bpm - 150.0).abs() < 0.05, "global bpm {bpm}");
    assert_eq!(report["engine"], "precision");
    let points = report["points"].as_array().unwrap();
    assert!(!points.is_empty());
    let first = points[0]["offset_ms"].as_f64().unwrap();
    assert!((first - 500.0).abs() < 5.0, "first red line at {first} ms");
    assert!(report["diagnostics"].as_array().unwrap().is_empty());
    // v3's findings are not ported: absent, not an empty "nothing found".
    assert!(report.get("findings").is_none());

    assert_eq!(text_run.status.code(), Some(0));
    let text = String::from_utf8(text_run.stdout).unwrap();
    let mut lines = text.lines();
    assert!(lines
        .next()
        .unwrap()
        .starts_with("// Generated by Overtone v"));
    let row = lines.next().expect("one red line at least");
    assert_eq!(row.split(',').count(), 8, "{row}");
    // Progress went to stderr, not into the red lines.
    assert!(!text.contains("decoded"));
    assert!(String::from_utf8_lossy(&text_run.stderr).contains("decoded"));
}

#[test]
fn white_noise_is_refused_with_its_reason() {
    let dir = scratch("noise");
    let path = dir.join("noise.wav");
    let mut seed = 99u64;
    let y: Vec<f32> = (0..44_100 * 10).map(|_| 0.8 * noise(&mut seed)).collect();
    write_wav(&path, &y);
    let json_run = run(&["analyze", path.to_str().unwrap(), "--json"]);
    let text_run = run(&["analyze", path.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(json_run.status.code(), Some(3));
    let report: serde_json::Value = serde_json::from_slice(&json_run.stdout).unwrap();
    assert!(report["global_bpm"].is_null(), "no BPM for noise: {report}");
    assert_eq!(report["engine"], "refused");
    assert!(report["points"].as_array().unwrap().is_empty());
    assert!(!report["diagnostics"].as_array().unwrap().is_empty());

    assert_eq!(text_run.status.code(), Some(3));
    assert!(text_run.stdout.is_empty(), "no red lines on stdout");
}

#[test]
fn a_missing_file_and_a_bad_command_line_say_so() {
    let missing = run(&["analyze", "no-such-file.wav", "--json"]);
    assert_eq!(missing.status.code(), Some(1));
    let report: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert!(report["error"].is_string());

    for args in [
        &[][..],
        &["analyse", "x.wav"][..],
        &["analyze"][..],
        &["analyze", "a.wav", "b.wav"][..],
        &["analyze", "a.wav", "--decimals"][..],
        &["analyze", "a.wav", "--persistence", "many"][..],
        &["analyze", "a.wav", "--frobnicate"][..],
    ] {
        let out = run(args);
        assert_eq!(out.status.code(), Some(2), "{args:?}");
        assert!(out.stdout.is_empty(), "{args:?}");
        assert!(String::from_utf8_lossy(&out.stderr).contains("usage:"));
    }
}
