//! The binary end to end: exit codes, stdout carrying only the result, and
//! the report's shape. Audio is synthesised into a scratch directory.

use std::path::{Path, PathBuf};
use std::process::{Command, Output};

fn scratch(tag: &str) -> PathBuf {
    let dir = std::env::temp_dir().join(format!("overtone-cli-{tag}-{}", std::process::id()));
    std::fs::create_dir_all(&dir).unwrap();
    dir
}

/// 16-bit mono PCM WAV at 44.1 kHz.
fn write_wav(path: &Path, samples: &[f32]) {
    let data = (samples.len() * 2) as u32;
    let mut b = Vec::new();
    b.extend_from_slice(b"RIFF");
    b.extend_from_slice(&(36 + data).to_le_bytes());
    b.extend_from_slice(b"WAVEfmt ");
    b.extend_from_slice(&16u32.to_le_bytes());
    b.extend_from_slice(&1u16.to_le_bytes());
    b.extend_from_slice(&1u16.to_le_bytes());
    b.extend_from_slice(&44_100u32.to_le_bytes());
    b.extend_from_slice(&(44_100u32 * 2).to_le_bytes());
    b.extend_from_slice(&2u16.to_le_bytes());
    b.extend_from_slice(&16u16.to_le_bytes());
    b.extend_from_slice(b"data");
    b.extend_from_slice(&data.to_le_bytes());
    for &s in samples {
        b.extend_from_slice(&((s.clamp(-1.0, 1.0) * 32767.0) as i16).to_le_bytes());
    }
    std::fs::write(path, b).unwrap();
}

/// Deterministic noise in [-0.5, 0.5).
fn noise(seed: &mut u64) -> f32 {
    *seed = seed.wrapping_mul(6364136223846793005).wrapping_add(1);
    ((*seed >> 33) as f64 / (1u64 << 31) as f64 - 0.5) as f32
}

/// Clicks at `bpm` from 0.5 s for `seconds`, every fourth one louder.
fn clicks(bpm: f64, seconds: f64) -> Vec<f32> {
    let sr = 44_100.0;
    let mut y = vec![0.0f32; (seconds * sr) as usize];
    let mut seed = 7u64;
    let mut k = 0usize;
    loop {
        let t = 0.5 + k as f64 * 60.0 / bpm;
        if t > seconds - 0.2 {
            break;
        }
        let gain = if k % 4 == 0 { 0.9 } else { 0.5 };
        let start = (t * sr) as usize;
        for i in 0..(0.03 * sr) as usize {
            let decay = (-(i as f64) / (0.004 * sr)).exp() as f32;
            y[start + i] += gain * decay * noise(&mut seed);
        }
        k += 1;
    }
    y
}

/// 16-bit mono PCM WAV at any rate.
fn write_wav_at(path: &Path, samples: &[f32], rate: u32) {
    write_wav(path, samples);
    let mut bytes = std::fs::read(path).unwrap();
    bytes[24..28].copy_from_slice(&rate.to_le_bytes());
    bytes[28..32].copy_from_slice(&(rate * 2).to_le_bytes());
    std::fs::write(path, bytes).unwrap();
}

/// Clicks at `bpm` rendered at `rate`, as [`clicks`] does at 44.1 kHz.
fn clicks_at(bpm: f64, seconds: f64, rate: u32) -> Vec<f32> {
    let sr = rate as f64;
    let mut y = vec![0.0f32; (seconds * sr) as usize];
    let mut seed = 7u64;
    let mut k = 0usize;
    loop {
        let t = 0.5 + k as f64 * 60.0 / bpm;
        if t > seconds - 0.2 {
            break;
        }
        let gain = if k % 4 == 0 { 0.9 } else { 0.5 };
        let start = (t * sr) as usize;
        for i in 0..(0.03 * sr) as usize {
            let decay = (-(i as f64) / (0.004 * sr)).exp() as f32;
            y[start + i] += gain * decay * noise(&mut seed);
        }
        k += 1;
    }
    y
}

fn run(args: &[&str]) -> Output {
    Command::new(env!("CARGO_BIN_EXE_overtone-cli"))
        .args(args)
        .output()
        .expect("the binary runs")
}

#[test]
fn a_click_track_reads_its_tempo() {
    let dir = scratch("clicks");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 30.0));
    let json_run = run(&["analyze", path.to_str().unwrap(), "--json"]);
    let text_run = run(&["analyze", path.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        json_run.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&json_run.stderr)
    );
    let report: serde_json::Value =
        serde_json::from_slice(&json_run.stdout).expect("stdout is one JSON document");
    let bpm = report["global_bpm"].as_f64().unwrap();
    assert!((bpm - 150.0).abs() < 0.05, "global bpm {bpm}");
    assert_eq!(report["engine"], "precision");
    let points = report["points"].as_array().unwrap();
    assert!(!points.is_empty());
    let first = points[0]["offset_ms"].as_f64().unwrap();
    assert!((first - 500.0).abs() < 5.0, "first red line at {first} ms");
    assert!(report["diagnostics"].as_array().unwrap().is_empty());
    // v3's findings are not ported: absent, not an empty "nothing found".
    assert!(report.get("findings").is_none());

    assert_eq!(text_run.status.code(), Some(0));
    let text = String::from_utf8(text_run.stdout).unwrap();
    let mut lines = text.lines();
    assert!(lines
        .next()
        .unwrap()
        .starts_with("// Generated by Overtone v"));
    let row = lines.next().expect("one red line at least");
    assert_eq!(row.split(',').count(), 8, "{row}");
    // Progress went to stderr, not into the red lines.
    assert!(!text.contains("decoded"));
    assert!(String::from_utf8_lossy(&text_run.stderr).contains("decoded"));
}

#[test]
fn white_noise_is_refused_with_its_reason() {
    let dir = scratch("noise");
    let path = dir.join("noise.wav");
    let mut seed = 99u64;
    let y: Vec<f32> = (0..44_100 * 10).map(|_| 0.8 * noise(&mut seed)).collect();
    write_wav(&path, &y);
    let json_run = run(&["analyze", path.to_str().unwrap(), "--json"]);
    let text_run = run(&["analyze", path.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(json_run.status.code(), Some(3));
    let report: serde_json::Value = serde_json::from_slice(&json_run.stdout).unwrap();
    assert!(report["global_bpm"].is_null(), "no BPM for noise: {report}");
    assert_eq!(report["engine"], "refused");
    assert!(report["points"].as_array().unwrap().is_empty());
    assert!(!report["diagnostics"].as_array().unwrap().is_empty());

    assert_eq!(text_run.status.code(), Some(3));
    assert!(text_run.stdout.is_empty(), "no red lines on stdout");
}

#[test]
fn a_missing_file_and_a_bad_command_line_say_so() {
    let missing = run(&["analyze", "no-such-file.wav", "--json"]);
    assert_eq!(missing.status.code(), Some(1));
    let report: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert!(report["error"].is_string());

    for args in [
        &[][..],
        &["analyse", "x.wav"][..],
        &["analyze"][..],
        &["analyze", "a.wav", "b.wav"][..],
        &["analyze", "a.wav", "--decimals"][..],
        &["analyze", "a.wav", "--persistence", "many"][..],
        &["analyze", "a.wav", "--frobnicate"][..],
    ] {
        let out = run(args);
        assert_eq!(out.status.code(), Some(2), "{args:?}");
        assert!(out.stdout.is_empty(), "{args:?}");
        assert!(String::from_utf8_lossy(&out.stderr).contains("usage:"));
    }
}

#[test]
fn odd_rates_short_audio_and_junk_end_cleanly() {
    // The gates.py robustness probes, through the v4 engine.
    let dir = scratch("robust");
    let mut reports = Vec::new();
    for rate in [8_000u32, 96_000] {
        let path = dir.join(format!("clicks-{rate}.wav"));
        write_wav_at(&path, &clicks_at(150.0, 20.0, rate), rate);
        reports.push((rate, run(&["analyze", path.to_str().unwrap(), "--json"])));
    }
    let short = dir.join("short.wav");
    write_wav(&short, &clicks(150.0, 1.0));
    let short_run = run(&["analyze", short.to_str().unwrap()]);
    let junk = dir.join("notes.wav");
    std::fs::write(&junk, "not audio at all").unwrap();
    let junk_run = run(&["analyze", junk.to_str().unwrap()]);
    std::fs::remove_dir_all(&dir).ok();

    for (rate, out) in reports {
        assert_eq!(out.status.code(), Some(0), "{rate} Hz");
        let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
        let bpm = report["global_bpm"].as_f64().unwrap();
        assert!((bpm - 150.0).abs() < 0.05, "{rate} Hz read {bpm}");
    }
    // Exit 1 (could not load), with a message: not a panic (exit 101).
    for out in [short_run, junk_run] {
        assert_eq!(out.status.code(), Some(1));
        assert!(out.stdout.is_empty());
        assert!(String::from_utf8_lossy(&out.stderr).contains("cannot load"));
    }
}

#[test]
fn full_carries_the_evidence_an_analysis_object_needs() {
    let dir = scratch("full");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 30.0));
    let out = run(&["analyze", path.to_str().unwrap(), "--full"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(out.status.code(), Some(0));
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let evidence = &report["evidence"];
    assert_eq!(evidence["hop"], 128);
    assert_eq!(evidence["sample_rate"], 44_100);
    let len = |key: &str| evidence[key].as_array().unwrap().len();
    // The fitting envelope has librosa's centred frame count: 1 + n / hop.
    assert_eq!(len("onset"), 1 + 30 * 44_100 / 128);
    assert_eq!(len("attack_times"), len("attack_weights"));
    assert!(len("attack_times") >= 70, "{} attacks", len("attack_times"));
    assert!(len("beats") >= 70);
    assert_eq!(len("local_bpms"), len("beats"));
    assert!(len("points") >= 1);
    // Sections now say where their grid is, not only its tempo.
    let section = &report["sections"][0];
    let period = section["period_s"].as_f64().unwrap();
    assert!((60.0 / period - 150.0).abs() < 0.05, "period {period}");
    assert!(section["phase_s"].is_number());
}

/// A sustained triad, `seconds` long, at `amp`.
fn triad(root: f64, amp: f64, seconds: f64) -> Vec<f32> {
    let sr = 44_100.0;
    (0..(seconds * sr) as usize)
        .map(|i| {
            let t = i as f64 / sr;
            let tau = 2.0 * std::f64::consts::PI * t;
            (amp * ((tau * root).sin()
                + 0.6 * (tau * root * 1.2599).sin()
                + 0.6 * (tau * root * 1.4983).sin())) as f32
        })
        .collect()
}

#[test]
fn structure_reads_phrases_and_says_why_each_label() {
    // Quiet A minor, loud F major, twice: 16 s phrases, boundaries at 16/32/48.
    let dir = scratch("structure");
    let path = dir.join("abab.wav");
    let (a, b) = (triad(220.0, 0.12, 16.0), triad(174.61, 0.3, 16.0));
    write_wav(&path, &[a.clone(), b.clone(), a, b].concat());
    let out = run(&["structure", path.to_str().unwrap()]);
    let missing = run(&["structure", "no-such-file.wav"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let bounds: Vec<f64> = report["boundaries"]
        .as_array()
        .unwrap()
        .iter()
        .map(|v| v.as_f64().unwrap())
        .collect();
    assert_eq!(bounds.len(), 3, "{bounds:?}");
    for (found, truth) in bounds.iter().zip([16.0, 32.0, 48.0]) {
        assert!((found - truth).abs() <= 1.5, "{bounds:?}");
    }
    let sections = report["sections"].as_array().unwrap();
    let kinds: Vec<&str> = sections
        .iter()
        .map(|s| s["kind"].as_str().unwrap())
        .collect();
    assert_eq!(kinds, ["verse", "chorus", "verse", "chorus"]);
    let groups: Vec<u64> = sections
        .iter()
        .map(|s| s["group"].as_u64().unwrap())
        .collect();
    assert_eq!(groups, [0, 1, 0, 1]);
    assert!(sections.iter().all(|s| s["repeats"] == 2));
    assert!(sections[1]["level_db"].as_f64().unwrap() > sections[0]["level_db"].as_f64().unwrap());
    let energy = report["energy"].as_array().unwrap().len();
    assert_eq!(energy, 128, "one value per 0.5 s window");
    assert_eq!(report["rules"]["edge_blind_s"], 4.0);

    assert_eq!(missing.status.code(), Some(1));
    let failed: serde_json::Value = serde_json::from_slice(&missing.stdout).unwrap();
    assert!(failed["error"].is_string());
    for args in [
        &["structure"][..],
        &["structure", "a.wav", "b.wav"][..],
        &["structure", "--full"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
        assert!(bad.stdout.is_empty());
    }
}

#[test]
fn hitsound_proposes_every_object_with_alternatives_and_terms() {
    // Twelve bare circles on 150 BPM clicks: the prior keeps them bare,
    // and each proposal carries its alternatives and its terms.
    let dir = scratch("hitsound");
    let audio = dir.join("clicks-150.wav");
    write_wav(&audio, &clicks(150.0, 6.0));
    let mut map = String::from("osu file format v14\r\n[TimingPoints]\r\n500,400,4,2,1,70,1,0\r\n[HitObjects]\r\n");
    for k in 0..12 {
        map.push_str(&format!("256,192,{},1,0,0:0:0:0:\r\n", 500 + k * 400));
    }
    let map_path = dir.join("clicks.osu");
    std::fs::write(&map_path, map).unwrap();
    let out = run(&["hitsound", audio.to_str().unwrap(), map_path.to_str().unwrap()]);
    let missing_map = run(&["hitsound", audio.to_str().unwrap(), "no-such.osu"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(report["templates"], "baked");
    assert_eq!(report["profile"], "balanced");
    let units = report["units"].as_array().unwrap();
    assert_eq!(units.len(), 12);
    for unit in units {
        let proposal = &unit["proposal"];
        assert!(proposal["bank"].is_string());
        assert!(proposal["additions"].is_array());
        let probability = proposal["probability"].as_f64().unwrap();
        assert!((0.0..=1.0).contains(&probability), "{proposal}");
        // Alternatives with marginals, terms that replay the choice.
        let alternatives = unit["alternatives"].as_array().unwrap();
        assert!(!alternatives.is_empty());
        assert!(alternatives.iter().all(|a| (0.0..=1.0).contains(&a["probability"].as_f64().unwrap())));
        let terms = unit["terms"].as_array().unwrap();
        assert_eq!(terms.len(), 4);
        assert!(unit["transition_in"].is_number() || unit["transition_in"].is_null());
        assert_eq!(unit["tail"], false);
    }
    // Bare circles with a prior stay bare: the first proposal is normal.
    assert_eq!(units[0]["proposal"]["additions"].as_array().unwrap().len(), 0);
    assert!(report["timings_s"]["decide"].is_number());

    assert_eq!(missing_map.status.code(), Some(1));
    for args in [
        &["hitsound"][..],
        &["hitsound", "a.wav"][..],
        &["hitsound", "a.wav", "b.osu", "c.osu"][..],
        &["hitsound", "a.wav", "b.osu", "--profile"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
    }
}

#[test]
fn ramps_turns_a_click_track_into_one_line_and_refuses_bad_input() {
    let dir = scratch("ramps");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 30.0));
    let out = run(&["ramps", path.to_str().unwrap()]);
    let capped = run(&["ramps", path.to_str().unwrap(), "--max-lines", "1"]);
    let missing = run(&["ramps", "no-such-file.wav"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    let lines = report["lines"].as_array().unwrap();
    assert_eq!(lines.len(), 1, "{lines:?}");
    let bpm = lines[0]["bpm"].as_f64().unwrap();
    assert!((bpm - 150.0).abs() < 0.5, "one line at {bpm}");
    assert!(lines[0]["max_drift_ms"].as_f64().unwrap() <= 5.0);
    let tradeoff = report["tradeoff"].as_array().unwrap();
    assert_eq!(tradeoff.len(), 5);
    assert!(tradeoff.iter().all(|row| row["lines"].as_u64().unwrap() == 1));
    assert_eq!(report["recommend_ramps"], false);
    assert_eq!(report["elastic"]["degree"].as_u64().unwrap(), 1);

    assert_eq!(capped.status.code(), Some(0));
    let capped_report: serde_json::Value = serde_json::from_slice(&capped.stdout).unwrap();
    assert_eq!(capped_report["drift_ms"].as_f64().unwrap(), 1.0);

    assert_eq!(missing.status.code(), Some(1));
    for args in [
        &["ramps"][..],
        &["ramps", "a.wav", "b.wav"][..],
        &["ramps", "a.wav", "--drift", "0"][..],
        &["ramps", "a.wav", "--max-lines", "0"][..],
        &["ramps", "a.wav", "--bogus"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
    }
}

#[test]
fn hitsound_evidence_scores_every_attack_and_names_its_role() {
    let dir = scratch("evidence");
    let path = dir.join("clicks-150.wav");
    write_wav(&path, &clicks(150.0, 12.0));
    let out = run(&["hitsound-evidence", path.to_str().unwrap()]);
    let missing = run(&["hitsound-evidence", "no-such-file.wav"]);
    std::fs::remove_dir_all(&dir).ok();

    assert_eq!(
        out.status.code(),
        Some(0),
        "{}",
        String::from_utf8_lossy(&out.stderr)
    );
    let report: serde_json::Value = serde_json::from_slice(&out.stdout).unwrap();
    assert_eq!(report["templates"], "baked");
    let attacks = report["attacks"].as_array().unwrap();
    assert!(!attacks.is_empty());
    for attack in attacks {
        let classes = attack["classes"].as_array().unwrap();
        // All 13 classes, probabilities that sum to one.
        assert_eq!(classes.len(), 13, "{attack}");
        let total: f64 = classes
            .iter()
            .map(|c| c["probability"].as_f64().unwrap())
            .sum();
        assert!((total - 1.0).abs() < 1e-9, "{total}");
        // Each term's contribution replays its class's score.
        for class in classes {
            let terms = class["terms"].as_array().unwrap();
            assert!(!terms.is_empty());
            assert!(terms.iter().all(|t| t["feature"].is_string()
                && t["value"].is_number()
                && t["response"]["kind"].is_string()
                && t["contribution"].is_number()));
        }
        // The click grid proves bars, so the role sits on it.
        assert!(attack["role"]["division"].is_number());
        assert!(attack["role"]["metrical_weight"].is_number());
    }
    assert!(!report["sections"].as_array().unwrap().is_empty());

    assert_eq!(missing.status.code(), Some(1));
    for args in [
        &["hitsound-evidence"][..],
        &["hitsound-evidence", "a.wav", "b.wav"][..],
        &["hitsound-evidence", "--full"][..],
    ] {
        let bad = run(args);
        assert_eq!(bad.status.code(), Some(2), "{args:?}");
    }
}
